### ISSUE TITLE
Changelog for test-builds

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/website#3]
It would be convenient to see some info what is new in test-builds

**Comment by modos189** [comment]
I don't see an easy way to do that(

**Comment by johnd0e** [comment]
`git log`?

**Comment by modos189** [comment]
Now server does not store the git repository. Need to somehow pass hash of current commit and display only new changes. And if history is rewritten and last commit is lost, from whence is the change shown?

**Comment by johnd0e** [comment]
> Need to somehow pass hash of current commit and display only new changes.

We do not need track every single change.
With every deploy we can replace test-builds news with raw git log, from latest tag to HEAD.

**Comment by johnd0e** [comment]
This should be part of `deploy` script.

**Comment by johnd0e** [comment]
`git log` may be confusing it there are a lot of changes from different PRs (like now).
So may be better just list PRs in `Testing` column of 'Project 1'.

https://developer.github.com/v3/projects/columns/

**Comment by johnd0e** [comment]
Brief googling results (no particular order)
- https://github.com/nytimes/Chronicler
- https://github.com/github-changelog-generator/github-changelog-generator
  - https://github.com/github-changelog-generator/Github-Changelog-Generator/wiki/Alternatives
    (a lot of!!!)
- https://github.com/conventional-changelog
  - https://github.com/semantic-release/release-notes-generator
  - https://github.com/release-it/conventional-changelog
     - https://github.com/release-it/release-it
- https://github.com/zeit/release
- https://github.com/git-chglog/git-chglog
- https://github.com/lob/generate-changelog

some blogs reviews
- https://depfu.com/blog/changelogs-to-write-or-to-generate
- https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6

**Comment by modos189** [comment]
We refused to publish test-builds. Now the site publishes build artifacts of specific PR
